general:
  external_ip: 127.0.0.1
  http_port: 8667
  listen_interface: 0.0.0.0
  listen_port: 8667
  tftp_port: 69
  sync_service_type: 'asterisk_ami'
  # Number of trusted HTTP reverse-proxies before a phone can reach
  # wazo-provd. This is used to detect the device's IP address.
  # If 0, then the HTTP header X-Forwarded-For will be ignored.
  num_http_proxies: 0
rest_api:
  ip: 127.0.0.1
  port: 8666
auth:
  host: localhost
  port: 9497
  prefix: null
  https: false
amid:
  host: localhost
  port: 9491
  prefix: null
  https: false
bus:
    username: guest
    password: guest
    host: localhost
    port: 5672
    exchange_name: wazo-headers
syncdb:
    interval_sec: 86400
    start_sec: 60
