version: '3'
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  provd:
    image: wazopbx/xivo-provd
    volumes:
      - "../..:/usr/src/xivo-provisioning/"
      - "./etc/xivo/provd/provd.conf:/etc/xivo/provd/provd.conf"
    ports:
      - "8666"
      - "8667"
      - "69/udp"

  pluginserver:
    image: trinitronx/python-simplehttpserver
    volumes:
      - "./provd/plugins/pkgs:/var/www"
    ports:
      - "8080"
