general:
  plugin_server: http://pluginserver:8080/
  verbose: true
  listen_interface: 0.0.0.0
rest_api:
  ip: 0.0.0.0
auth:
  host: auth
bus:
    host: rabbitmq
syncdb:
    interval_sec: 86400
    start_sec: 60
