general:
  plugin_server: http://pluginserver:8080/
  verbose: true
  listen_interface: 0.0.0.0
database:
  uri: postgresql://wazo-provd:Secr7t@postgres/wazo-provd
rest_api:
  ip: 0.0.0.0
auth:
  host: auth
bus:
    host: rabbitmq
